### ISSUE TITLE
Documentation is key

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/LoadoutController#1]
OK boys here goes...I struggle with this aspect of it. When making changes to things and updating it is SUPER helpful to people like myself who don't understand code too well to have information on a few things.

1. Date of change
2. Who is making the change and lastly
3. What the changes were no matter how small and call it Vxxxxx.xxx if needed

example: 1.  Nichols - 5/3/17 - V00000.00001 - Wrote example of how to notate changes for others to understand what is changing on a different version. Until new version # is placed in the beginning of the comment all notes in Readme/changelog should be on that version without changes.

**Comment by Jmaster9999** [comment]
changes are documented, look at the Comits tab in git. Github automatically generates a changelog. Additionally in the releases tab there are version numbers and changes between versions. Once I fix this for good I'll create a wiki for the loadout controller showing every step in how to get it working.

**Comment by Jmaster9999** [comment]
Additionally the commits feature in github shows line for line changes, as well as allowing for titles and descriptions of changes.

**Comment by Jmaster9999** [comment]
https://github.com/Spearhead-Gaming-Milsim/LoadoutController/releases/tag/2.0

Should be the final version of the code, working on a wiki now

**Comment by Jmaster9999** [comment]
https://github.com/Spearhead-Gaming-Milsim/LoadoutController/wiki
documentation for installation done,
mirroring to the readme file
