### ISSUE TITLE
Confusing to my mind...

### ISSUE THREAD

**Issue by coachwn** [Spearhead-Gaming-Milsim/LoadoutController#2]
OK How is this better than the old Loadoutcontroller.sqf that is in my mission file? Why do I need to have a randomizer and other sqf files running just to check and make sure that peoples gear is loading properly?

**Comment by Jmaster9999** [comment]
The randomizer does not run, It is bundled with the loadout controller for convenience (it's there if you want to use it). The only thing that runs are CreateLoadout.sqf and Setloadout.sqf

**Comment by Jmaster9999** [comment]
This version of the loadout controller is structured differently and is way more efficient (it only runs when you re-spawn). Additionally it fixed a critical bug with the old version which causes a massive decrease in frame-rate after people re-spawn.

**Comment by Jmaster9999** [comment]
Closed, Question was answered and there is a rework in progress to increase usability.
